# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_groupmanager',
            new_name='is_group_manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_openingmanager',
            new_name='is_opening_manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_revokationmanager',
            new_name='is_revocation_manager',
        ),
    ]
