# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0002_auto_20170325_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lp', models.IntegerField()),
                ('K', models.IntegerField()),
                ('Lamda1', models.IntegerField()),
                ('Lamda2', models.IntegerField()),
                ('Gamma1', models.IntegerField()),
                ('Gamma2', models.IntegerField()),
            ],
        ),
    ]
