# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0003_security_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security_parameters',
            name='Gamma1',
        ),
        migrations.RemoveField(
            model_name='security_parameters',
            name='Gamma2',
        ),
    ]
