# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0008_auto_20170326_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_joined',
            field=models.BooleanField(default=False),
        ),
    ]
