# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0010_auto_20170326_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('C', models.CharField(max_length=1024)),
                ('S1', models.CharField(max_length=1024)),
                ('S2', models.CharField(max_length=1024)),
                ('S3', models.CharField(max_length=1024)),
                ('S4', models.CharField(max_length=1024)),
                ('T1', models.CharField(max_length=1024)),
                ('T2', models.CharField(max_length=1024)),
                ('T3', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Ai',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ei',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
