# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0012_messeges_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messeges',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
