# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0013_messeges_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Xi',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='messeges',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
